= fping-exporter - Measure RTT and packet loss and export data to be picked up by node_exporter
:stylesheet: asciidoc.css
:toc: left

== Repositories

* Primary development repository: https://git.ypbind.de/cgit/fping-exporter/
* Backup repository: https://github.com/Bobobo-bo-Bo-bobo/fping-exporter/

== Preface
Except for the https://github.com/prometheus/blackbox_exporter[Blackbox Exporter] there is no exporter
to measure round-trip time and packet loss.

== Requirements
This script requires https://fping.org/[fping], bash and GNU awk.

== Running the exporter
This script should be run as service. It will write the result into the directory, given by the `-O`/ `--output-directory` option (default is `/tmp`) into the file `fping-exporter.prom`.

https://github.com/prometheus/node_exporter[Prometheus node_exporter] should be configured to read files from a given directory by setting `--collector.textfile` and `--collector.textfile.directory=...`
and export it's content for scrape requests.

== Command line parameters

[width="100%",cols="<26%,<30%,<44%",options="header",]
|===
|_Parameter_ |_Description_ |_Default_
|`-B <factor>` / `--backoff-factor=<factor>` |Backoff factor |1.0
|`-O` / `--output-directory` |Output directory to write `fping-exporter.prom` file with results |`/tmp`
|`-V` / `--version` |Show version information |-
|`-c <count>` / `--packet-count=<count>` |Number of ICMP packets to send |10
|`-h` / `--help` |Show help text |-
|`-i <sec>` / `--interval=<sec>` |Send ping requests to hosts every <sec> second |300
|`-r <count>` / `--retry=<count>` |Retry limit |3
|`-t <tos>` / `--tos=<tos>` |Set type of service flag to <tos> |`0x00`
|`-x <msec>` / `--max=<msec>` |Maximal value for round-trip time to be considered as valid in msec |`5000`
|===

== Running as unprivileged user

For security reasons, it's not recommended to run the exporter as `root`.
To allow `fping` to create raw network sockets `root` permissions are required.

Some distributions don't allow this by either enabling the `SUID` bit in the file permissions (file should be owned by `root`) or by not setting
the `cap_net_raw` capability.

On modern systems using the capability flag instead of classic file permissions should be used:

Capabilities can be queried using the `getcap` command:

....
root@server:~# which fping
/usr/bin/fping
root@server:~# getcap /usr/bin/fping
root@server:~# 
....

and can be set by the `setcap` command:

....
root@server:~# setcap cap_net_raw=ep /usr/bin/fping
root@server:~# getcap /usr/bin/fping
/usr/bin/fping cap_net_raw=ep
....

== Licenses

=== fping-exporter

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.

